apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverse-proxy
spec:
  selector:
    matchLabels:
      app: backend
      tier: udagram-reverse-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        tier: udagram-reverse-proxy
    spec:
      restartPolicy: Always
      containers:
        - name: udagram-reverse-proxy
          image: rodpassos/udagram-reverse-proxy
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
