apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
  labels:
    app: frontend
    tier: udagram-frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
    tier: udagram-frontend
  ports:
    - name: "8100"
      port: 8100
      targetPort: 80
