apiVersion: v1
kind: Service
metadata:
  name: udagram-api-feed
  labels:
    app: backend
    tier: udagram-api-feed
spec:
  selector:
    app: backend
    tier: udagram-api-feed
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
